---
# Manage databases on existing SQL instances
- name: "Create Database"
  hosts: windows
  connection: winrm

  vars:
    ansible_winrm_server_cert_validation: "ignore"
    db_name: ''
    db_host: ''
    db_host_user: ''
    db_host_pwd: ''
    db_state: ''

  tasks:
    - name: "Ensure {{ db_name }} is present on {{ ansible_hostname }}"
      mssql_db:
        name: "{{ db_name }}"
        login_host: "{{ db_host }}"
        login_user: "{{ db_host_user }}"
        login_password: "{{ db_host_pwd }}"
        state: "{{ db_state }}"
