- name: "Deploy website"
  hosts: windows
  connection: winrm

  vars:
    ansible_winrm_server_cert_validation: "ignore"
    website_name: MyWinApp
    website_version: 0.1
    website_dir: "c:\\inetpub\\wwwroot\\"
    website_database_pool: "windb"
    website_dbuser: "{{ dbuser | default('website') }}"
    website_dbpass: "{{ dbpass | default('Password123!') }}'"

  tasks:
    - set_fact:
        website_database_servers: "{{ groups[website_database_pool] | list }}"

    - name: "Build iisstart.htm and save to {{ website_dir }}\\iistart.htm"
      win_template:
        src: templates/iisstart.htm.j2
        dest: "{{ website_dir }}\\iisstart.htm"

    - name: "Copy application files to {{ website_dir }}"
      win_copy:
        src: files/
        dest: "{{ website_dir }}"
