---
- name: Install Apache from an MSI
  hosts: windows
  connection: winrm

  vars:
    msi_url: 'http://mirror.cc.columbia.edu/pub/software/apache//httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi'
    msi_dest: 'C:\Users\Administrator\Downloads\httpd-2.2.25-win32-x86-no_ssl.msi'

  tasks:
    - name: Download the Apache installer
      win_get_url:
        url: "{{ msi_url }}"
        dest: "{{ msi_dest }}"

    - name: Install MSI
      win_msi:
        path: "{{ msi_dest }}"
        state: present
