- name: "PowerShell Module"
  hosts: windows

  vars:
    nuget_repository_url: https://nuget.acme.com/
    nuget_repository_name: MyPrivateRepo
    name: PowershellModule
    state: present

  tasks:
    - name: "Ensure state of powershell module"
      win_psmodule:
        repository: "{{ nuget_repository_name }}"
        url: "{{ nuget_repository_url }}"
        name: "{{ name }}"
        state: "{{ state }}"
