- name: "service"
  hosts: windows

  vars:
    ansible_winrm_server_cert_validation: "ignore"
    win_service_name: RSCDsvc
    win_service_start_mode: auto
    win_service_state: started
    win_service_comment: BMC BladeLogic Agent

  tasks:
    - name: "Ensure state of service"
      win_service:
        name: "{{ win_service_name }}"
        start_mode: "{{ win_service_start_mode }}"
        state: "{{ win_service_state }}"
