---
- hosts: all
  gather_facts: yes
  connection: winrm

  vars:
    win_updates_categories:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      - Updates
      - ServicePacks

  tasks:
    - name: "Update packages"
      win_updates:
        category_names: "{{ win_updates_categories }}"
        state: installed
