- name: "Create VM from template in VMware"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    vmware_guest_name: "{{ nios_host_record_host }}"
    vmware_guest_template: "RHEL7"
    vmware_guest_vcpus: 1
    vmware_guest_memory: 1024
    vmware_guest_os: rhel7_64Guest
    vmware_guest_disk_size_gb: 30
    vmware_guest_disk_type: thin
    vmware_guest_network: "VM Network"
    vmware_guest_machine_environment: "staging"
    vmware_guest_machine_class: "unknown"
    vmware_guest_datacenter: "europe-central-fr1"
    vmware_guest_cluster: "POD01"
    vmware_guest_datastore: "gluster_datastore_01"
    vmware_guest_annotation:
      - "environment={{ vmware_guest_machine_environment }}"
      - "class={{ vmware_guest_machine_class }}"
    vmware_guest_validate_certs: False
    vmware_guest_dumpfacts: False
    vmware_guest_wait_for_ip_address: True
    vmware_guest_resource_pool: 'Production'
    vmware_guest_state: poweredon
    vmware_guest_nic_device_type: vmxnet3
    vmware_guest_nic_type: static
    vmware_guest_network_nic_dvswitch: "dvSwitch01"
    vmware_guest_nic_ip: "{{ lookup('nios', 'record:host', filter={'name': nios_host_record_fqdn }) }}"
    vmware_guest_nic_netmask: "{{ nios_host_record_subnet | ipaddr('netmask') }}"

  tasks:
    - debug:
        var: vmware_guest_nic_ip

    - name: "Ensure state of virtual instance in vmware"
      vmware_guest:
        validate_certs: "{{ vmware_guest_validate_certs }}"
        esxi_hostname: "{{ vmware_guest_esxhost | default(omit) }}"
        datacenter: "{{ vmware_guest_datacenter }}"
        name: "{{ vmware_guest_name | default(mandatory )}}"
        cluster: "{{ vmware_guest_cluster | default(omit) }}"
        resource_pool: "{{ vmware_guest_resource_pool | default(omit) }}"
        template: "{{ vmware_guest_template }}"
        folder: "{{ vmware_guest_folder | default(mandatory) }}"
        guest_id: "{{ vmware_guest_os }}"
        disk:
          - size_gb: "{{ vmware_guest_disk_size_gb }}"
            type: "{{ vmware_guest_disk_type }}"
            datastore: "{{ vmware_guest_datastore }}"
        networks:
          - name: "{{ vmware_guest_network }}"
            dvswitch_name: "{{ vmware_guest_network_nic_dvswitch | default(omit) }}"
            device_type: "{{ vmware_guest_nic_device_type | default(omit) }}"
            type: "{{ vmware_guest_nic_type | default(omit) }}"
            ip: "{{ vmware_guest_nic_ip | ipaddr('address') or default(omit) }}"
            netmask: "{{ vmware_guest_nic_netmask | ipaddr('netmask') or default(omit) }}"
            gateway: "{{ vmware_guest_nic_ip | ipaddr('1') | ipaddr('address') or default(omit) }}"
            start_connected: true
        hardware:
          memory_mb: "{{ vmware_guest_memory }}"
          num_cpus: "{{ vmware_guest_vcpus }}"
        wait_for_ip_address: "{{ vmware_guest_wait_for_ip_address }}"
        annotation: "{{ vmware_guest_annotation | join(',') }}"
        state: "{{ vmware_guest_state }}"
      register: r_vmware_guest

    - name: "debug"
      debug:
        var: r_vmware_guest
        verbosity: 2
