---
- hosts: all
  become: yes
  gather_facts: yes

  vars:
    autorun: true
    linux_update: no
#    linux_rhs_org_id: ''
#    linux_rhs_activation_key: ''

  tasks:
    - name: "victorock.linux"
      include_role:
         name: victorock.linux
