apache_services:
  - httpd

apache_ports:
  - 80/tcp
  - 443/tcp

apache_packages:
  - httpd
  - php
  - php-mysql
  - libsemanage-python

apache_sebooleans:
  - httpd_can_network_connect
  - httpd_can_network_connect_db
